/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heraldrygen;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
/*     @Test void appHasAGreeting() {
        HeraldryGen classUnderTest = new HeraldryGen();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    } */
}
