/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heraldrygen;

import java.awt.Graphics2D;
import java.awt.Component;

public class HeraldryGen {

    public static Component comp;
    public static Graphics2D compGraph = (Graphics2D) comp.getGraphics();

    public static void main(String[] args) {
    }
}
